### ISSUE TITLE
Remove `vendor` from `.gitignore`

### ISSUE THREAD

**Issue by afbora** [lukasleitsch/kirby-blade#24]
The vendor directory does not come when downloaded as a ZIP, so the `vendor` directory should be removed from the `.gitignore` file. 

According to the information I learned from @lukasbestle; when a plugin installed with global composer, `composer-installer` package already deletes `vendor` directory in the plugin.

**Comment by lukasbestle** [comment]
A bit of background: Keeping the necessary Composer dependencies in the repo allows users to install the plugin via ZIP download and as a Git submodule, both of which are preferred by many users who are not comfortable with CLI tools or prefer a simple setup. Because our Composer installer handles deleting the `vendor` directory on installation via Composer, the committed `vendor` directory does not break installation via Composer.

You can read more about this [in our docs](https://getkirby.com/docs/guide/plugins/plugin-setup-composer).

**Comment by lukasleitsch** [comment]
It was an active decision to exclude the `vendor` folder and don't commit this folder. We know about the other installation option, but we need a composer setup to have the option to use the composer autoloader to load the blade component classes.

In the project `compose.json` we define the path for the blade components. Blade will only load components inside the namespace `App\View\Components`. (Yes, we know this feature is undocumented)

```
  "autoload": {
    "psr-4": {
      "App\\View\\Components\\": "site/components/"
    }
  },
```

The Laravel Blade package gets regular updates. Without the committed `composer.lock` and the `vendor` folder you'll always get an up-to-data blade version without updates of this package.

I'm sorry to tell you that we only provide the installation via composer.
